### ISSUE TITLE
can you create a new organization?

### ISSUE THREAD

**Issue by tanersekmen** [ayyucedemirbas/TurkeyLearningInitiative#52]
Hi,

Would it be more logical to create an organization and support it publicly instead of local repository ?

**Comment by ayyucedemirbas** [comment]
Organization'ımız zaten var, ancak orada websitesi üzerinde çalışıyoruz.

**Comment by tanersekmen** [comment]
Anladım çok teşekkür ederim bilgi verdiğin için. Ben repo sadece senin profilinde gibi düşünmüştüm ondan dolayı böyle bir issue açmıştım. Kusura bakma lütfen 🙏

**Comment by tanersekmen** [comment]
Aslında ben bunu public bir github organizasyon reposu olarak söylemiştim. Bunu kapatabiliriz 🙏
