### ISSUE TITLE
Öneri: Derslerin Branch'lere Ayrılması

### ISSUE THREAD

**Issue by AimTune** [ayyucedemirbas/TurkeyLearningInitiative#53]
Merhaba,

Repository'e katkı sunmak için clone'lamak çile gibi görünüyor ve ayrıca da buradan sürekli upload etmek de sağlıklı görünmüyor(Belki bazı notların yeni sürümleri olacak web arayüzünden PDF gibi binary bir dosyayı modified hale getirmekle kim uğraşır diye düşünüyorum). Bunun için dersleri branch'ler üstünde tutup master(main) branch'de linkleri verebiliriz. Hem o derse katkı sunmak isteyen olursa da o branch'e geçip notlarını ekler-günceller. Hem bu çalışma insanların git'in sadece commit-push'tan ibaret olmadığını branch'ler arasında geçiş nasıl yapılır vs. gibi kullanımlarına da alışmasını sağlar diye düşünüyorum.

Herkese iyi çalışmalar.

**Comment by ayyucedemirbas** [comment]
Merhaba, websitemize yakında ders notları yüklenebiliyor olacak. Bu sebeple burada şimdilik sadece PR'ları kabul edip olabildiğince çok not bulmaya çalışacağız.
